<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://globsest.com/testsoap"
           xmlns:tns="http://globsest.com/testsoap"
           elementFormDefault="qualified">

    <xs:complexType name="UserShort">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="login" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="UserFull">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="login" type="xs:string"/>
            <xs:element name="password" type="xs:string"/>
            <xs:element name="roles" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="GetAllUsersRequest" type="xs:anyType"/>
    <xs:element name="GetAllUsersResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="users" type="tns:UserShort" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GetUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="tns:UserFull"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="DeleteUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="DeleteUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="success" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CreateUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="login" type="xs:string"/>
                <xs:element name="password" type="xs:string"/>
                <xs:element name="roles" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CreateUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="success" type="xs:boolean"/>
                <xs:element name="errors" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="UpdateUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="login" type="xs:string"/>
                <xs:element name="password" type="xs:string"/>
                <xs:element name="roles" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="UpdateUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="success" type="xs:boolean"/>
                <xs:element name="errors" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
